{{- if .Values.auditWebhook.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "botkube.name" . }}-audit-webhook
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: auditwebhook
    app: botkube
data:
  audit_config.yaml: |
  {{- with .Values.auditWebhook.config }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
