apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube.fullname" . }}-communication-secret
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  comm_config.yaml: |
    # Communication settings
    communications:
      # Settings for Slack
      slack:
        enabled: {{ .Values.communications.slack.enabled }}
        channel: {{ .Values.communications.slack.channel }}                  # Slack channel name without '#' prefix where you have added BotKube and want to receive notifications in
        token: {{ .Values.communications.slack.token }}
        notiftype: {{ .Values.communications.slack.notiftype }}              # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified) 

      # Settings for Mattermost
      mattermost:
        enabled: {{ .Values.communications.mattermost.enabled }}
        url: {{ .Values.communications.mattermost.url }}                       # URL where Mattermost is running. e.g https://example.com:9243
        token: {{ .Values.communications.mattermost.token }}                   # Personal Access token generated by BotKube user
        team: {{ .Values.communications.mattermost.team }}                     # Mattermost Team to configure with BotKube
        channel: {{ .Values.communications.mattermost.channel }}               # Mattermost Channel for receiving BotKube alerts
        notiftype: {{ .Values.communications.mattermost.notiftype }}           # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)

      # Settings for ELS
      elasticsearch:
        enabled: {{ .Values.communications.elasticsearch.enabled }}
        server: {{ .Values.communications.elasticsearch.server }}              # e.g https://example.com:9243
        username: {{ .Values.communications.elasticsearch.username }}
        password: {{ .Values.communications.elasticsearch.password }}
        # ELS index settings
        index:
          name: {{ .Values.communications.elasticsearch.index.name }}
          type: {{ .Values.communications.elasticsearch.index.type }}
          shards: {{ .Values.communications.elasticsearch.index.shards }}
          replicas: {{ .Values.communications.elasticsearch.index.replicas }}

      # Settings for Webhook
      webhook:
        enabled: {{ .Values.communications.webhook.enabled }}
        url: {{ .Values.communications.webhook.url }}                          # e.g https://example.com:80
