apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube.fullname" . }}-communication-secret
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  comm_config.yaml: |
  {{- with .Values.communicationConfig }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
