apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "botkube.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  resource_config.yaml: |
    {{- with .Values.config }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

  access_config.yaml: |
    {{- with .Values.accessConfig }}
      {{- toYaml . | nindent 4 }}
    {{- end }}  

