{{- if .Values.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botkube.fullname" . }}-kubeconfig
  labels:
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config: {{ .Values.kubeconfig }}
{{- end }}
